### ISSUE TITLE
Incorrect value for the "data-domain" attribute of the script in the header

### ISSUE THREAD

**Issue by sawa-ko** [productdevbookcom/v-plausible#2]
### Describe the bug

Currently the plugin is setting the script in the page header with the wrong value of the "data-domain" attribute. It is actually set as the url of the api set in the "plausible.init.apiHost" option of the plugin options and not in the "plausible.init.domain" option.

Because of this, the statistics do not appear in the plausible dashboard as this attribute has an incorrect value.

## Script generate by plugin

![image](https://github.com/productdevbookcom/v-plausible/assets/56084970/31690b50-5989-45b9-af2d-f11d7bcda34e)

## Script generated by plausible dashboard

![image](https://github.com/productdevbookcom/v-plausible/assets/56084970/ded9aef1-1ac6-49ca-9b19-c10997464e58)

## Options

```ts
  plausible: {
    init: {
      apiHost: 'https://analytics.naeko.moe',
      trackLocalhost: false,
      domain: 'https://next.naeko.moe',
    },
    settings: {
      enableAutoPageviews: true,
      enableAutoOutboundTracking: true,
    },
  }
```

### Reproduction

https://next.naeko.moe

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 6.08 GB / 15.74 GB
  Binaries:
    Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by productdevbook** [comment]
```
  init: {
    domain: 'domain.com',
    apiHost: 'https://host.com',
    trackLocalhost: true,
  },
...
```

readme same used. please `domain` https:// delete

**Comment by productdevbook** [comment]
soon fixed domain

**Comment by sawa-ko** [comment]
Thanks!

**Comment by sawa-ko** [comment]
@productdevbook Sorry, I saw that you published the version in github, but not in npm, will it be available also in npm?

**Comment by productdevbook** [comment]
> @productdevbook Sorry, I saw that you published the version in github, but not in npm, will it be available also in npm?

Very interesting, I've just published it. Would you check

**Comment by sawa-ko** [comment]
Yes, the npmjs version is now available.

By the way, i noticed some strange behavior. If the domain option is not set, then according to the documentation it will be set to `location.hostname`, however when you visit the site, the domain attribute appears as localhost.

![image](https://github.com/productdevbookcom/v-plausible/assets/56084970/f908dd26-e275-4256-b995-5d00b4785130)
